[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
norecursedirs="tests/helpers"

[tool.black]
line-length = 120
exclude = '''
/(
    \.git
  | \.hypothesis
  | \.tox
  | \.vscode
  | \__pycache__
  | build
  | dist
  | docs
)/
'''

[tool.flake8]
max-line-length = 120
